spring.application.name=be_accesa

# PostgreSQL DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/CV_Matcher
spring.datasource.username=postgres
spring.datasource.password=changeme

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

aws.s3.region=us-east-1
aws.s3.accessKey=42D531317A4638D8898B
aws.s3.secretKey=ZveS4hxeqquaxgXU8foX82tWnoQSVPOHBEzN3R66
aws.s3.endpoint=https://s3.filebase.com
aws.s3.bucket=cv-storage

